server:
  port: 8092 #项目端口

spring:
  application:
    name: movie-cinema
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guns_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: duguxiaobiao
    db-name: guns_rest #用来搜集数据库的所有表
    filters: wall,mergeStat


logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
#  file: guns-user.log

dubbo:
  scan:
    base-packages: com.stylefent.guns.cinema.service
  protocol:
    name: dubbo
    port: 21884
  registry:
    address: zookeeper://localhost:2181
  #设置服务提供，都是轮询的方式
  provider:
    loadbalance: roundrobin


mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/cinema/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.cinema.common.puersistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true #开启mybatis驼峰式命名规则自动转换
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

